name: lighthouse
description: Entrance examination counseling platform for teenagers

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_screenutil: ^5.0.0
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.3
  google_sign_in: ^4.5.9
  flutter_web_auth: ^0.2.4
  http: ^0.12.0+4
  uuid: ^3.0.1
  flutter_webview_plugin: ^0.3.11
  kakao_flutter_sdk: ^0.5.4
  dio:
  json_annotation:
  shared_preferences:
  platform:
  package_info:

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/navigation/
    - assets/images/
  fonts:
    - family: NotoSansCJKkr
      fonts:
        - asset: fonts/NotoSansCJKkr-Medium.otf
        - asset: fonts/NotoSansCJKkr-Regular.otf
        - asset: fonts/NotoSansCJKkr-Bold.otf